Add support for Razer PWM PC Fan Controller
LibreHardwareMonitor/LibreHardwareMonitor pull request #1090
Opened 2023-06-08 03:26 UTC by wlkmanist

I am on Win8.1, so I can't use Synapse 3 and can't write a plugin for FanControl (V63 is the latest working version for me, with LHM  lib 0.8.7). But I can backport this code to 0.8.7 or use it as is.
Controls works in full range (from 0% to 100%). Also already fixed issue with fan hotplug.

![image](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/19557325/3c74d515-3e1e-4e43-8c4e-beef7b2b712f)

2023-06-08 06:03 UTC, wlkmanist commented
Yea, now its works fine, but I can't test it on newer FanControl versions.

2023-06-14 10:06 UTC, PhyxionNL requested changes
Some small things, thanks 😎

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +            do
To normal while.

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +    private readonly HidDevice _device;
Can you reformat this document?

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +                do
Can be normal while.

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +    private Packet __WriteAndRead(Packet packet)
Naming.., no __

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +            var cts = new CancellationTokenSource(DEVICE_READ_TIMEOUT_MS);
Switch to Stopwatch perhaps?

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +            catch (System.IO.IOException) // Unexpected device disconnect or fan plug/unplug
Include System.IO :)

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +                    do
Can also be normal while.

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerFanController.cs
> +    private const int DEFAULT_SPEED_CHANNEL_POWER = 50;
Part of reformatting, but all these consts can just be at top of the file.

2023-06-14 10:06 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerGroup.cs
> +    private readonly List<IHardware> _hardware = new();
Also reformat.

2023-06-15 10:53 UTC, wlkmanist commented
I don't know, how to hide the device if it disconnected. Is it possible?

2023-06-15 11:09 UTC, PhyxionNL commented
> I don't know, how to hide the device if it disconnected. Is it possible?

You can choose not to add the device in the group when it's disconnected. For dynamic add/remove you need to implement IHardwareChanged, see an example:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Network/NetworkGroup.cs

For HidSharp I think you can use their Changed event:
https://github.com/IntergatedCircuits/HidSharp/blob/master/HidSharp/DeviceList.cs#L40

2023-06-15 11:10 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Controller/Razer/RazerGroup.cs
> +    private readonly List<IHardware> _hardware = new();
No, there's no new line after break statement on L34 for example.

2023-06-15 11:11 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Mutexes.cs
> +    private static Mutex _razerDeviceMutex;
Rename _razorDeviceMutex to _razorMutex.

2023-06-15 11:33 UTC, wlkmanist commented
> > I don't know, how to hide the device if it disconnected. Is it possible?
> 
> You can choose not to add the device in the group when it's disconnected. For dynamic add/remove you need to implement IHardwareChanged, see an example: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Network/NetworkGroup.cs
> 
> For HidSharp I think you can use their Changed event: https://github.com/IntergatedCircuits/HidSharp/blob/master/HidSharp/DeviceList.cs#L40

Ok, mayby I will try to add that

2023-06-15 14:39 UTC, PhyxionNL commented
> > > I don't know, how to hide the device if it disconnected. Is it possible?
> > 
> > 
> > You can choose not to add the device in the group when it's disconnected. For dynamic add/remove you need to implement IHardwareChanged, see an example: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Network/NetworkGroup.cs
> > For HidSharp I think you can use their Changed event: https://github.com/IntergatedCircuits/HidSharp/blob/master/HidSharp/DeviceList.cs#L40
> 
> Ok, maybe I will try to add that

Do you still want to do this?

2023-06-15 15:24 UTC, wlkmanist commented
> > > > I don't know, how to hide the device if it disconnected. Is it possible?
> > > 
> > > 
> > > You can choose not to add the device in the group when it's disconnected. For dynamic add/remove you need to implement IHardwareChanged, see an example: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Network/NetworkGroup.cs
> > > For HidSharp I think you can use their Changed event: https://github.com/IntergatedCircuits/HidSharp/blob/master/HidSharp/DeviceList.cs#L40
> > 
> > 
> > Ok, maybe I will try to add that
> 
> Do you still want to do this?

Probably not, or much later, maybe with another PR. This is not a device that user must plug/unplug while pc is enabled.

2023-06-15 15:26 UTC, merged