Bugfix: Fan and Temp data missing #780
LibreHardwareMonitor/LibreHardwareMonitor pull request #1438
Opened 2024-08-21 10:07 UTC by keif888

This is a fix for #780 IT8655E which shows incorrect/missing information for fans and temps.

I have tested this on my ASUS Prime B350M-A, through a number of restarts, sleeps and hibernates, and I no longer see the incorrect fan speeds, incorrect temperatures or missing temperatures.

Inspiration came from [Linux it87](https://github.com/frankcrawford/it87/blob/14b1de2fb49db4e73b58177bc43daa71ceb8e92f/it87.c#L3870) where the interaction with the IT8655E does a set_bank before every interaction with a port.

In theory this fix can be applied to other IT86 chipsets as per FEAT_BANK_SEL as shown [here](https://github.com/frankcrawford/it87/blob/14b1de2fb49db4e73b58177bc43daa71ceb8e92f/it87.c#L709) for the IT8655.
As I can't test other chipsets I have not made the changes.

Setting _requiresBankSelect to true for other chipsets that have this issue may fix them as well.  
eg. Issue #760 could be fixed as per below.

LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\IT87XX.cs
```
@@ -135,6 +135,7 @@ internal class IT87XX : ISuperIO
                Temperatures = new float?[6];
                Fans = new float?[6];
                Controls = new float?[5];
+                _requiresBankSelect = true;  // Fix #760
                break;

            case Chip.IT8688E:
```

2024-08-21 11:01 UTC, keif888 commented
The following issues may also be addressed with this pull.
#246, #277, #349, #433, #709, #735, #737, #855, #952, #970, #1148, #1336.

2024-08-22 08:09 UTC, PhyxionNL requested changes
Thanks for looking into this :)

2024-08-22 08:09 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/IT87XX.cs
> +    private readonly bool _requiresBankSelect;  // Fix #780 Set to true for those chips that need a SelectBank(0) to fix dodgy temps and fan speeds
I think just this comment is enough, so the ones below can be removed.

2024-08-22 08:20 UTC, keif888 commented
1st time I'm using a pull request and review.  Hoping that I'm getting the workflow right.

2024-08-22 09:06 UTC, merged