NET5 initial support
LibreHardwareMonitor/LibreHardwareMonitor pull request #312
Opened 2020-10-10 16:17 UTC by Pomianowski

Initial support for NET 5.0 (for the current v5.0.0-rc.1)
[https://dotnet.microsoft.com/download/dotnet/5.0](https://dotnet.microsoft.com/download/dotnet/5.0)

2020-11-12 07:54 UTC, Pomianowski commented
Fixes for the official .NET 5 release. Update Microsoft.Win32.Registry and System.IO.Ports to stable 5.0.0. Works with Visual Studio 16.8.0

2020-11-16 00:04 UTC, Pomianowski commented
#actions/virtual-environments/issues/2022

2020-11-16 04:03 UTC, robertmclaws commented
If you follow [my instructions here](https://github.com/dotnet/core/issues/5120#issuecomment-726362230), you can probably get this build working.

2020-11-16 17:00 UTC, PhyxionNL commented
Holding this off until the VS image is fixed.

2020-11-21 21:17 UTC, Pomianowski commented
@PhyxionNL Yey, It is working now

2020-11-22 09:42 UTC, PhyxionNL requested changes
Some misc.

2020-11-22 09:42 UTC, PhyxionNL commented on .github/workflows/main.yml
> -
Can you undo this.

2020-11-22 09:42 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Ring0.cs
> +#elif NET5_0
Can you merge these checks, this can be similar to the one in KernelDriver I think.

2020-11-22 09:42 UTC, PhyxionNL commented on LibreHardwareMonitorLib/LibreHardwareMonitorLib.csproj
> +    <PackageReference Include="Microsoft.Win32.Registry">
Can you change this to normal PackageReference format? I.e.     `<PackageReference Include="Contoso.Utility.UsefulStuff" Version="3.6.0" />`

2020-11-24 09:01 UTC, merged