Added PM table entry for Zen 3 (key = 0x00380805 )
LibreHardwareMonitor/LibreHardwareMonitor pull request #640
Opened 2022-01-24 17:33 UTC by DevTechProfile

Sorry, Master to Master. Was to lazy to create a specific branch for that small code adjustment.

2022-01-24 17:36 UTC, DevTechProfile commented
Tested on my machine with Ryzen 9 5900X (fyi, 2 cores per CCD are disabled due to testing purposes). 

![image](https://user-images.githubusercontent.com/30285858/150834787-406775ea-3a4e-4c59-a8ad-28e9be9272a5.png)

2022-01-24 17:42 UTC, PhyxionNL requested changes
Thanks 👍 Values match with Ryzen Master?

2022-01-24 17:42 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/RyzenSMU.cs
> +                // Zen Raven Ridge APU
Undo.

2022-01-24 17:42 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/RyzenSMU.cs
> +                // Zen 2
Undo.

2022-01-24 17:42 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/RyzenSMU.cs
> +                // Zen 3
Also point + formatting below :)

2022-01-24 17:52 UTC, DevTechProfile commented
> Thanks 👍 Values match with Ryzen Master?

No, it doesn't match the HWiNFO values.
![image](https://user-images.githubusercontent.com/30285858/150837268-6d7a650c-4df6-4e4e-87ad-b4917784846a.png)

2022-01-24 17:55 UTC, DevTechProfile commented
Fabric, Uncore, Memory clocks are correct

2022-01-27 10:42 UTC, DevTechProfile commented
> > Fabric, Uncore, Memory clocks are correct
> 
> It's likely that the other items are on a different index, you can try looping through the values and see if anything matches Ryzen Master. Keep in mind that the scale might be different 👍

Where do I get the scale from? Does the SMU itself provice these scales?

2022-01-27 10:43 UTC, PhyxionNL commented
Trial and error :) But so far it always seems to be 1 or 1000.

2022-01-27 11:04 UTC, DevTechProfile commented
> Trial and error :) But so far it always seems to be 1 or 1000.

Look at the screenshot. HWiNFO shows something like 12A and the SMU readout with scale = 1 looks like chaos. :-D

2022-01-27 11:05 UTC, PhyxionNL commented
It's probably on a different index, I recommend looping through all of them and see which value matches with Ryzen Master or HWiNFO.

2022-01-27 12:12 UTC, DevTechProfile commented
Gonna check this later this evening.

2022-02-05 10:03 UTC, PhyxionNL commented
> Gonna check this later this evening.

Any update?

2022-02-07 07:46 UTC, DevTechProfile commented
> > Gonna check this later this evening.
> 
> Any update?

Yes, indeed. I tried to identify the correct values in the array. Impossible because for CPU TDC e.g. there are 3 values that match with with the HWiNFO sensor. What makes it even more difficult to find a match is an update cycle offset. 

Is there any documentation to be able to identify the indices of the array?

The only entries which work properly are

`          
{ 48, new SmuSensorType { Name = "Fabric", Type = SensorType.Clock, Scale = 1 } },
{ 50, new SmuSensorType { Name = "Uncore", Type = SensorType.Clock, Scale = 1 } },
{ 51, new SmuSensorType { Name = "Memory", Type = SensorType.Clock, Scale = 1 } },
`

I will adjust the code and push an update later.

2022-02-07 15:59 UTC, closed without merging