Update the minimum framework to net472
LibreHardwareMonitor/LibreHardwareMonitor pull request #723
Opened 2022-04-30 00:50 UTC by coreyshuman

This PR sets the minimum targeted framework to .NET 4.7.2 in all of the projects in the solution. This PR achieves the intent of the discussion in issue #650. This PR also updates the README to match these updated requirements.

This PR is helpful because Visual Studio 2022 natively includes .NET 4.7.2, but support for 4.6.2 - 4.7.1 requires additional installation.

Additionally, due to the use of C#10 File Scoped Namespaces in the lib project, the solution [no longer compiles in VS2019](https://dotnetcoretutorials.com/2021/09/20/file-scoped-namespaces-in-c-10/). Because of this, I added a line in the README stating that "Compiling LibreHardwareMonitor requires Visual Studio 2022." 

If we would like to change this verbiage, or if someone knows a workaround to retain VS2019 support, please let me know and I'll make those updates to this PR.

Fixes #650

2022-04-30 22:00 UTC, pomianowski commented
Well, we can also add a `.vsconfig` file with the required components and it will all work while still being backwards compatible. Simply Visual Studio will tell you what libraries are missing.

2022-05-01 03:46 UTC, coreyshuman commented
The solution was already moved to .NET 4.7.0 in this commit:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/c3c7925181b1296ac551999fdcf47970e4f27f23

And the desktop app moved to .NET 4.7.2 in this commit:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/dbdedb86c4cb5298d64503c2c8fee7d093e39e47

The goal of this PR is to synchronize that minimum version across projects.

2022-05-01 08:14 UTC, PhyxionNL requested changes

2022-05-01 08:14 UTC, PhyxionNL commented on LibreHardwareMonitorLib/LibreHardwareMonitorLib.csproj
> +    <TargetFrameworks>net472;netstandard2.0;net5.0;net6.0</TargetFrameworks>
I would prefer to keep this on net47 for now.

2022-05-01 08:14 UTC, PhyxionNL commented on README.md
> +*Compiling LibreHardwareMonitor requires [Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2022?view=vs-2022).*
This should be moved to **How to compile the application below** as this also includes other stuff.

2022-05-01 12:09 UTC, coreyshuman commented
@PhyxionNL updated as requested! Also just noticed `net452\LibreHardwareMonitor.exe` in the "How to Compile" section and updated to match these changes.

2022-05-01 13:13 UTC, merged