Add Update Interval
LibreHardwareMonitor/LibreHardwareMonitor pull request #730
Opened 2022-05-01 20:00 UTC by tacal666

2022-06-23 14:52 UTC, PhyxionNL requested changes

2022-06-23 14:52 UTC, PhyxionNL commented on LibreHardwareMonitor/UI/MainForm.cs
> +
Reformat this block.

2022-06-23 14:52 UTC, PhyxionNL commented on LibreHardwareMonitor/UI/MainForm.cs
> +        }
Remove.

2022-06-26 11:00 UTC, tacal666 commented
if someone would make change is ok i'm traveling
thanks

2022-11-12 12:51 UTC, closed without merging