Windows storage spaces
LibreHardwareMonitor/LibreHardwareMonitor pull request #871
Opened 2022-11-06 15:47 UTC by marcadamsge

I had the same problem as this issue #396, I use a windows storage space on two nvmes and I would like to monitor the temperature of the nvmes. There's window's [storage management api](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/stormgmt/storage-management-api-classes) that can be used to explore the Disks and PhysicalDisks. With this PR I can now see my two nvmes:

![Screenshot 2022-11-06 161141](https://user-images.githubusercontent.com/22477080/200180396-b53ed53f-abcf-46b8-a008-fa4eb0c68415.png)

The `Msft Storage Space` is a storage space on top of the two `Kingston SFYRS1000G`

2022-11-07 14:24 UTC, PhyxionNL requested changes

2022-11-07 14:24 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +            string serialNumber = ExtractSerialNumber((string)diskDrive.Properties["SerialNumber"].Value);
I've mentioned this before in another PR, but a serial number is not a reliable way to map for HDDs, I have two HDDs here with the same serial number.

2022-11-07 14:24 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +                if (serialNumber != null && virtualDiskMap.ContainsKey(serialNumber))
Does the normal "instance" above still need to be added then?

2022-11-07 14:24 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +        var physicalDiskMap = new Dictionary<string, PhysicalDisk>();
These WMI classes are not available on Windows 7, this needs to be checked.

2022-11-07 14:24 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +            var sn = ExtractSerialNumber((string)physicalDisk["ObjectId"]);
sn > serialNumber.

2022-11-07 14:24 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +        var virtualDiskMap = new Dictionary<string, List<PhysicalDisk>>();
Might as well use a value tuple (string DeviceId, ulong Size) instead of the PhysicalDisk.

2022-11-07 14:24 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +            var virtualDiskSn = ExtractSerialNumber((string)virtualToPhysicalDisk["VirtualDisk"]);
sn > SerialNumber (also below)

2022-11-07 14:24 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +            string serialNumber = ExtractSerialNumber((string)diskDrive.Properties["SerialNumber"].Value);
I see MSFT_PhysicalDisk and Win32_DiskDrive both using a DeviceID. This is probably more reliable and possibly wouldn't require extracting the serial then, have you tried this?

2022-11-08 13:09 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +            string serialNumber = ExtractSerialNumber((string)diskDrive.Properties["SerialNumber"].Value);
Yeah, I think device id is the way to go. The ObjectID might not be needed as you should be able to traverse through the WMI objects, see comment below. I'll mark this as resolved.

2022-11-09 18:29 UTC, marcadamsge commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +                var virtualDiskObjectId = ExtractReferenceObjectID((string)diskToVirtualDisk["VirtualDisk"]);
Yeah, that was a bit dirty.. That's the first way I found to use these WMI classes. The references in the association classes are returned as strings when used with `SELECT * FROM ASSOCIATION_TABLE`, you can't do much with them.
I'm not sure what you meant exactly? Anyway I've replaced these queries with `ASSOCIATORS OF` queries, there's no more ID parsing needed. I think this is how the API is intended to be used.

2022-11-09 19:00 UTC, PhyxionNL requested changes
Thanks! Few small nits left, rest looks good!

2022-11-09 19:01 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +        var physicalDiskMap = new Dictionary<string, PhysicalDisk>();
Yeah, let's just use the new API here.

2022-11-10 17:26 UTC, marcadamsge commented on LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs
> +                        var physicalDiskInstance = AbstractStorage.CreateInstance($"\\\\.\\PHYSICALDRIVE{physicalDisk.Item1}", physicalDisk.Item1, physicalDisk.Item2, scsi, settings);
Sure! 👍

2022-11-10 17:33 UTC, merged

2022-11-10 17:34 UTC, PhyxionNL commented
Thanks a lot @marcadamsge in getting this added.