Add support for ASRock Z790 Taichi/Z790 Taichi Carrara.
LibreHardwareMonitor/LibreHardwareMonitor pull request #962
Opened 2023-02-02 03:21 UTC by papa12804

Add support for fans and temps, but voltage readings in NCT6686D chip#1 is range from 0x106 to 0x114.
The `_voltageRegisters` in `Nct677X` is range from 0x120 to 0x13C, there needs some revise.

2023-02-23 12:21 UTC, PhyxionNL commented
Do you still want to work on this PR @papa12804?

2023-02-24 01:59 UTC, papa12804 commented
I can't come up with some good ideas for this now, adding brand judgments to `Nct677X` will make it messy.

2023-02-24 09:19 UTC, PhyxionNL commented
Hmm, NCT6686D (and NCT6683D) should use the same voltage registers as NCT6687D. I'll leave some feedback though :)

2023-02-24 09:22 UTC, PhyxionNL requested changes

2023-02-24 09:22 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Motherboard/Identification.cs
> +                return Model.Z790_Taichi;
This line can go away.

2023-02-24 09:22 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs
> +
Remove

2023-02-24 09:22 UTC, PhyxionNL commented on LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs
> +                        v.Add(new Voltage("+1.8V PROC Voltage", 0));
Follow file naming scheme:
PROC > CPU
PCH > Chipset.

Also the + can be removed from 1.8, 0.82 and 1.05V (but keep 3.3V).

2023-02-25 02:28 UTC, papa12804 commented
> Hmm, NCT6686D (and NCT6683D) should use the same voltage registers as NCT6687D. I'll leave some feedback though :)

I think each brand has its own NCT6686D or NCT6683D or NCT6687D firmware, so the location of the fan, temperature and voltage registers may vary.

2023-02-25 07:35 UTC, merged